### ISSUE TITLE
Uncluster markers when there is layers control on the map

### ISSUE THREAD

**Issue by wsenjer** [ghybs/Leaflet.MarkerCluster.LayerSupport#1]
Hello, 
Thank you for the great plugin. 
I'm building a website where I'm implementing a checkbox to enable/disable clustering of the map.

The code works when there is no `Layers Control` attached to the map.

```
    $('input:checkbox[name=clustering]').click(function() {
        if($(this).is(':checked')) { //Show markers as a cluster.
                 // Remove the markers.
                 map.removeLayer(geojson_markers);
                 // Add the markers to the cluster group.
                 geojson_markers.addTo(markercluster);
                 // Add the cluster group to the map.
                 map.addLayer(window.markercluster); 
        } else { //Show markers as a indiviuals.
                 markercluster.clearLayers(); // Remove the layers of the cluster
                 geojson_markers.addTo(map); // Add the individual markers group to the map
        }
    });
```

The problem is that line `geojson_markers.addTo(map);` has no effect on the map. Even though the clustering part is working.

**Comment by ghybs** [comment]
Hi,

Thank you for your feedback!

If my understanding is correct, your `markercluster` is an `L.markerClusterGroup.layerSupport`.
Then you want to add your `geojson_markers` group into it so that it clusters, except when your checkbox is unticked, you would like that group not to cluster?

Be noted that the `L.markerClusterGroup.layerSupport` will "remember" any group that is added to it, so that it clusters again when it is re-added to map later on. To prevent clustering, you have to call the `checkOut()` method first.

If the `geojson_markers` is the only group to be clustered into `markercluster`, you might be interested in my other plugin [Leaflet.MarkerCluster.Freezable](https://github.com/ghybs/Leaflet.MarkerCluster.Freezable), with which you can directly call `enableClustering()` and `disableClustering()` methods.

If there are other groups that go into the same `markercluster`, you might also be interested in my other plugin [Leaflet.FeatureGroup.SubGroup](https://github.com/ghybs/Leaflet.MarkerCluster.Freezable), with which you can call `setParentGroupSafe()` method to tell whether markers should be added into a parent group (your  `markercluster`, in order for markers to cluster) or directly to the map (unclustered).

Hope this helps.

**Comment by wsenjer** [comment]
[Leaflet.MarkerCluster.Freezable](https://github.com/ghybs/Leaflet.MarkerCluster.Freezable) solved the issue. Thank you very much.
