### ISSUE TITLE
How can I use this plugin in Angualr 2+?

### ISSUE THREAD

**Issue by helenpaprem** [ghybs/Leaflet.MarkerCluster.LayerSupport#16]
I have tried to use this plugin in angular 7. But I can't use it due to the several dependency issues.
How can I use it in angular 2 +?

**Comment by ghybs** [comment]
Hi,

This plugin in itself does not have any runtime dependency:
https://github.com/ghybs/Leaflet.MarkerCluster.LayerSupport/blob/v2.0.1/package.json
(Apart from Leaflet and Leaflet.markercluster, obviously)

Since you mention using Angular2+, what you _may_ have an issue with could be missing typings. In that case, this might help you: https://github.com/ghybs/Leaflet.TileLayer.Fallback/issues/11

Without specific details on your issue, it is almost impossible for me helping you any further.

Please feel free to ask for help on Stack Overflow, you will reach a wider audience. Make sure to provide enough details and code so that people can reproduce your issue.

**Comment by ghybs** [comment]
Closing due to lack of feedback.
