### ISSUE TITLE
Working with JSON data and Pie Chart

### ISSUE THREAD

**Issue by doctor343434** [ghybs/Leaflet.MarkerCluster.LayerSupport#18]
It is really a great plugin. I have 2 questions about the plugin I was curious about
1) How can we work with JSON data and make sliders
2) The pie chart that I mean by grouping the colors according to the defined colors in the groupings.

**Comment by ghybs** [comment]
Hi @doctor343434,

Thank you for your nice feedback!

I am not sure I fully understand your 2 questions, sorry. Sounds to me like you should ask them on Stack Overflow to reach a wider audience; please make sure to provide enough details so that people understand what you are trying to achieve.

Good luck!
