### ISSUE TITLE
leaflet marker cluster

### ISSUE THREAD

**Issue by jivthesh** [ghybs/Leaflet.MarkerCluster.LayerSupport#24]
can i directly add a geojson file to marker cluster ?if so how can i do it

**Comment by ghybs** [comment]
Hi,

I am not sure I understand exactly what you are trying to achieve? 

In case you have GeoJSON compliant data in a separate file, you could:
1. Load the file content
2. Parse the content into a JS object (typically with `JSON.parse`)
3. Convert the JS object containing the GeoJSON data into Leaflet layers with `L.geoJSON`
4. Add the Leaflet GeoJSON Layer Group into a MarkerClusterGroup, so that point features are clustered

If you need further help on how to use Leaflet and/or Leaflet.markercluster, please consider asking on StackOverflow, because you will reach a wider audience there.

The issues in this GitHub repo are for bugs.

**Comment by jivthesh** [comment]
> Hi,
> 
> I am not sure I understand exactly what you are trying to achieve?
> 
> In case you have GeoJSON compliant data in a separate file, you could:
> 
> 1. Load the file content
> 2. Parse the content into a JS object (typically with `JSON.parse`)
> 3. Convert the JS object containing the GeoJSON data into Leaflet layers with `L.geoJSON`
> 4. Add the Leaflet GeoJSON Layer Group into a MarkerClusterGroup, so that point features are clustered
> 
> If you need further help on how to use Leaflet and/or Leaflet.markercluster, please consider asking on StackOverflow, because you will reach a wider audience there.
> 
> The issues in this GitHub repo are for bugs.

**Comment by jivthesh** [comment]
ok thanks sorry for raising this as an issue.
