### ISSUE TITLE
Slider cluster with dynamic php data

### ISSUE THREAD

**Issue by jrupeja** [ghybs/Leaflet.MarkerCluster.LayerSupport#5]
Hey,

I am using drupal and want to use this slider plugin.

I am not using geojson data instead i am using dynamic php data array and  using it as 
 layerGroup = L.layerGroup([marker1, marker2, marker3, polyline]);

i have all the markers based on slider but not able to cluster it right now.
Will be glad if  you can help me out in this.

Thanks,
Jay

**Comment by ghybs** [comment]
Hi,

I guess you are talking about using LeafletSlider plugin together with MCG.LayerSupport?
Please note that LeafletSlider expects a `time` property in your layers' `feature` property, as if they were built from GeoJSON.

Please feel free to ask for help on Stack Overflow to receive a larger audience.
I could help when I have some spare time…
Consider sharing your source code and reproducing your issue on an online editing tool (JSFiddle, Plunker, JSBin…) so that people can provide you with detailed support.

Additionally, please note that MCG cannot cluster non-point data like polylines.

Hope this helps.

**Comment by jrupeja** [comment]
my only concern is i am not using GeoJSON.

i am using can say:
var marker1 = L.marker([11.6640943, 92.7475599], {time: "2013-01-22 08:42:26+01"});
        var marker2 = L.marker([28.5916316,77.1717474], {time: "2013-01-22 10:00:26+01"});
        var marker3 = L.marker([51.7, 7.7], {time: "2013-01-22 10:03:29+01"});
        var marker4 = L.marker([51.6, 7.2], {time: "2013-01-22 10:07:29+01"});
        var marker5 = L.marker([51.5, 7.1], {time: "2013-01-22 10:25:29+01"});

layerGroup = L.layerGroup([marker1, marker2, marker3]);
var sliderControl = L.control.sliderControl({layer:layerGroup, follow: false});
        myMap.addControl(sliderControl);
        sliderControl.startSlider();

and want to cluster these points based on slider movement.

Thanks,
Jay

**Comment by jrupeja** [comment]
Also, im Getting error in source,

uncaught type error: marker.checkIn is not a function
also with layer support,  error occurred that its not a function

**Comment by ghybs** [comment]
Hi,

Please did you have a look at the source code of the example?
https://github.com/ghybs/Leaflet.MarkerCluster.LayerSupport/blob/master/examples/mcgLayerSupport-leafletslider.html#L63

Hope this helps.

**Comment by jrupeja** [comment]
Yes i did but with this my slider wont show up.

BTW, Thanks for you help. I figured it out. There was problem with js include.
